// How Typst builds its own reference documentation
// =================================================
//
// A summary of findings from reading the `typst` repository, written up as a
// design reference for building Twyla's own reference docs. Twyla already uses
// the typst crates internally, so most of this machinery is reusable.
//
// TL;DR: Typst does NOT use rustdoc/Markdown. It compiles its reference *as a
// Typst document*. Stdlib metadata (including the `///` doc comments) is scraped
// at compile time by attribute macros, baked into the binary, and then exposed
// back to Typst markup through a small reflection API. The doc comments
// themselves are Typst markup, evaluated with `eval(.., mode: "markup")`.

#set page(width: 21cm, margin: 2cm)
#set heading(numbering: "1.1")
#show raw.where(block: true): set block(fill: luma(245), inset: 8pt, radius: 4pt, width: 100%)

= Overview

The reference is a custom pipeline in the `docs/` crate (`typst-docs`). It is
*not* generated by rustdoc, and it does not run any Markdown renderer
(`pulldown-cmark` and friends are absent from the codebase entirely). Instead it
treats the whole reference as a Typst document and compiles it with the normal
Typst compiler.

Two content sources are stitched together:

/ Prose pages: hand-written `.typ` files under `docs/content/` (e.g.
  `reference/language/`, `reference/library/foundations.typ`). Plain Typst
  markup authored directly.

/ Stdlib metadata: extracted from the Rust source — the `///` doc comments on
  every function, type, and element, plus titles, parameters, keywords, and
  return types.

= Compile-time extraction (Rust)

Every stdlib item is annotated with an attribute macro from
`crates/typst-macros/`:

#table(
  columns: 2,
  stroke: 0.5pt + luma(200),
  [`#[func]`],  [functions — `func.rs`],
  [`#[elem]`],  [elements — `elem.rs`],
  [`#[ty]`],    [types — `ty.rs`],
)

During macro expansion, `util.rs::documentation()` reads the `#[doc = "..."]`
attributes (which is what `///` comments desugar to), strips the leading space
Rust inserts, and concatenates them into a single string.

That string — together with name, title, parameter docs, keywords, and a
`DefSite { path, key }` — is baked into the generated `NativeFuncData` /
`NativeTypeData` struct. So the docs travel with the compiled binary.

#block(fill: luma(245), inset: 8pt, radius: 4pt, width: 100%)[
  Example shape of what the macro emits (`create_func_data`):
  ```rust
  NativeFuncData {
      name: "abs",
      title: "Absolute",
      docs: "Calculates the absolute value ...",  // from the /// comments
      def_site: Some(DefSite { path: file!(), key: <unique> }),
      keywords: &[...],
      // params each carry their own scraped docs
  }
  ```
]

= Build-time reflection (Typst)

The `typst-docs` binary compiles `docs/main.typ`. The reference pages don't
hard-code function lists; they *query* the stdlib through a reflection API:

- Rust side: `docs/src/reflect.rs` exposes `describe_func` / `describe_param` /
  `describe_ty`, surfacing the baked-in metadata.
- Typst side: `docs/components/reflect.typ` + `category.typ` call
  `stdx.describe(..)` and render the returned dict (name, title, docs, params,
  returns, keywords) into each reference page.

This is why the docs always match the current API — there is no second copy of
the signatures to keep in sync.

= The key subtlety: doc comments are Typst markup, not Markdown

This is the part most likely to surprise. The doc-comment string is not
Markdown — it is *Typst markup*, evaluated at render time. See
`docs/components/live.typ`:

```typst
eval(markup, scope: scope, mode: "markup")
```

A small scope of helpers is injected so comments can do more than prose:

```typst
#let scope = (
  example: example,           // ```example blocks -> rendered + run
  docs-figure: docs-figure,
  docs-table: docs-table,
  short-or-long: short-or-long,
)
```

So a ```` ```example ```` block inside a `///` comment is a Typst raw block
handled by the `example` function (which compiles and renders the snippet), not
a Markdown code fence.

== Hot reload via DefSite

Because each item carries a `DefSite { path, key }`, `live-docs` can re-`read()`
the actual Rust source file and re-evaluate the *current* comment text instead
of the version baked into the binary (`docs-in-source` / `docs/src/live.rs`).
Edit a doc comment, refresh, see the change — no recompile needed.

= Key files

#table(
  columns: 2,
  stroke: 0.5pt + luma(200),
  [`docs/src/main.rs`],            [entry point; orchestrates the docs build],
  [`docs/src/reflect.rs`],         [reflection API: stdlib metadata -> Typst],
  [`docs/src/live.rs`],            [parses `///` comments out of Rust source (hot reload)],
  [`docs/src/world.rs`],           [custom Typst `World` for the docs build],
  [`docs/src/search.rs`],          [walks output HTML, builds `search.json`],
  [`crates/typst-macros/src/func.rs`], [`#[func]` — scrapes + bakes function docs],
  [`crates/typst-macros/src/util.rs`], [`documentation()` — reads `#[doc=..]` attrs],
  [`docs/components/category.typ`],    [renders a reference page from reflection data],
  [`docs/components/live.typ`],        [`eval`s doc-comment markup; hot reload],
  [`docs/content/**/*.typ`],           [hand-written prose pages],
)

= Notes for Twyla

Since Twyla already depends on the typst crates, the reusable pieces are:

+ *Attribute macros that scrape `///` comments.* If Twyla's API surface is
  defined with similar `#[func]`-style macros, reuse the `documentation()`
  pattern to bake docs into the item metadata. If not, the alternative is
  parsing the Rust source with `syn` at docs-build time (Typst does both — baked
  copy + live re-read).

+ *Reflection API.* A thin Rust function that hands item metadata to Typst
  markup as a plain dict is the heart of the system — it removes any duplicated
  signature lists.

+ *Docs-as-Typst.* Authoring doc comments in Typst markup (rather than Markdown)
  is what unlocks runnable `example` blocks. Worth adopting if Twyla pages want
  live, rendered examples — which, as an SSG built on typst, it gets nearly for
  free.

+ *DefSite hot reload* is a nice-to-have, not essential for a first cut. Start
  with the baked-in `eval(markup, mode: "markup")` path and add source re-reads
  later.

+ *Search* is a pure post-process: walk the emitted HTML for metadata elements
  and write a JSON index. Decoupled from everything above.
